### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by martinraie** [aarnaud/vault-pki-exporter#1]
We're running vault-pki-exporter in docker and created following simple Dockerfile. Would you like to add it to the project?
```Dockerfile
FROM golang:alpine
WORKDIR /go/src/app
COPY . .
RUN go build cmd/main.go
EXPOSE 9333
CMD ["./main"]
```

**Comment by aarnaud** [comment]
Hi, 

can you push a PR ? 

Also, a multistage Dockerfile is better to avoid a huge image

**Comment by aarnaud** [comment]
Hi @martinraie 

I added a Dockerfile, let me know if it's good for you and close this issue in a same time

Thanks,

**Comment by martinraie** [comment]
This Dockerfile is perfect. Thank you.
